### ISSUE TITLE
Verweis auf DSAG ADT Leitfaden

### ISSUE THREAD

**Issue by se38** [ceedee666/modern-abap-curriculum#1]
Hallo Christian,

super Initiative!

Im Kapitel "[Installing Eclipse and the ABAP Development Tools](https://github.com/ceedee666/modern-abap-curriculum/blob/main/docs/hello_world.md#installing-eclipse-and-the-abap-development-tools)" könntest du auf den [DSAG-Leitfaden](https://1dsag.github.io/ADT-Leitfaden) verweisen.

Grüße, Uwe

**Comment by ceedee666** [comment]
Solved in [e39c823](https://github.com/ceedee666/modern-abap-curriculum/commit/e39c823af571088dd7299bbd0a5557139b160829)
The link to the DSAG-Leitfaden was already in the reference section. Now I also added it to the description of the installation process.
